### ISSUE TITLE
Decoder 数据类型时异常

### ISSUE THREAD

**Issue by uouuou** [hprose/hprose-golang#100]
type Time time.Time

func (t Time) String() string {
	return time.Time(t).Format("2006-01-02 15:04:05")
}

func (t Time) MarshalJSON() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

func init() {
	hprose.RegisterValueEncoder((*Time)(nil), hprose.GetValueEncoder((*time.Time)(nil)))
}

这样配置的情况下调度会出现异常：
hprose/io: can not cast time.Time to models.Time

**Comment by andot** [comment]
```go
type Time time.Time

func (t Time) String() string {
	return time.Time(t).Format("2006-01-02 15:04:05")
}

func (t Time) MarshalJSON() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

func init() {
	hprose.RegisterValueEncoder(Time{}, hprose.GetValueEncoder(time.Time{}))
	hprose.RegisterValueDecoder(Time{}, hprose.GetValueDecoder(time.Time{}))
}
```

最新的 v3.0.0-beta1 用上面的代码已经可以成功传输自定义 Time 类型了。

**Comment by uouuou** [comment]
> ```go
> type Time time.Time
> 
> func (t Time) String() string {
> 	return time.Time(t).Format("2006-01-02 15:04:05")
> }
> 
> func (t Time) MarshalJSON() ([]byte, error) {
> 	return []byte("\"" + t.String() + "\""), nil
> }
> 
> func init() {
> 	hprose.RegisterValueEncoder(Time{}, hprose.GetValueEncoder(time.Time{}))
> 	hprose.RegisterValueDecoder(Time{}, hprose.GetValueDecoder(time.Time{}))
> }
> ```
> 
> 最新的 v3.0.0-beta1 用上面的代码已经可以成功传输自定义 Time 类型了。

好的，收到！！
