### ISSUE TITLE
golang 服务端发布只能发布struct方法么，对于接口类型的发布是否支持呢

### ISSUE THREAD

**Issue by czyt** [hprose/hprose-golang#102]
目前看代码是不支持的。

**Comment by andot** [comment]
接口在反射后也是获取到接口背后的实际类型（可能是结构体，也可能是其它类型），所以是支持的。

**Comment by czyt** [comment]
> 接口在反射后也是获取到接口背后的实际类型（可能是结构体，也可能是其它类型），所以是支持的。

谢谢回复。在Go语言里面实际还是太依赖于具体的实现类了😂
