### ISSUE TITLE
Why can work well without ClassManager.Register when use custom struct

### ISSUE THREAD

**Issue by yuyi98** [hprose/hprose-golang#11]
// hps_001 project main.go
package main

import (
    "github.com/hprose/hprose-go"
    "net/http"
    _ "reflect"
)

type FloatPara struct {
    Id   int32
    Tag  string
    Desc string
    Tm   int32
}

type FloatData struct {
    Id   int32
    Para []FloatPara
}

func getMeasList() FloatData {
    return FloatData{22, []FloatPara{FloatPara{11, "float001", "desc_float001", 11111}, FloatPara{22, "float002", "desc_float002", 22222}}}
}

func main() {
    //hprose.ClassManager.Register(reflect.TypeOf(FloatPara{}), "Para")
    //hprose.ClassManager.Register(reflect.TypeOf(FloatData{}), "Data")

```
service := hprose.NewHttpService()
service.AddFunction("getMeasList", getMeasList)
http.ListenAndServe(":8080", service)
```

}

// hpc_001 project main.go
package main

import (
    "fmt"
    "github.com/hprose/hprose-go"
    _"reflect"
)

type FloatPara struct {
    Id   int8
    Tag  string
    Desc string
    Tm   int16
}

type FloatData struct {
    Id   int32
    Para []FloatPara
}

type Stub struct {
    GetMeasList func() FloatData
}

func main() {
    //hprose.ClassManager.Register(reflect.TypeOf(FloatPara{}), "FloatPara")
    //hprose.ClassManager.Register(reflect.TypeOf(FloatData{}), "FloatData")
    client := hprose.NewClient("http://127.0.0.1:8080")

```
var ro *Stub
client.UseService(&ro)

aa := ro.GetMeasList()
fmt.Println(aa)
```

}

it can work well, why?

**Comment by andot** [comment]
手动调用 ClassManager.Register 是可选的，不是必须的。在没有手动调用的情况下，是按照结构体本身的名字来进行序列化和反序列化的，因此只要名字是一致的，手动调用 ClassManager.Register 的过程可以省略。只要客户端和服务器端定义的类名（结构体名）相同，就可以相互传输。

**Comment by yuyi98** [comment]
有没有具体如何对函数进行序列化和反序列化的规则说明？
每种语言对函数的定义不同，是如何进行函数映射？
比较迷糊的是不知道Go语言定义的函数在其它语言中是如何定义，有没有相应的说明文档？

**Comment by andot** [comment]
hprose 对函数接口的映射是动态的，客户端和服务器端不需要完全一致，只要按照相容的类型来定义就可以了。比如服务器端定义的参数是 float64，客户端把参数定义成 int32 也是可以的，甚至定义成 string 都可以（但前提是传递的数据可以转换为 float64，否则调用时会报错，当然这也是意料之中的事情），数组，slice，List 这三种类型，于其他语言的数组、列表、集合等类型可以相互映射，定义成什么都可以。对象的传递在其他语言中只要字段名一致就可以了，字段个数不同的，多出来的字段会被忽略，对象的类名如果在两端定义的不一致，可以用 ClassManager.Register（其他语言中也有对应的这个方法，只是方法名的大小写可能有差异），来定义成一致的别名。另外，map 类型和对象类型也可以相互映射，但 map 的 key 的类型需要是字符串类型。

**Comment by andot** [comment]
最后说一下多值返回，对于 go 语言的多值返回，在其他语言的客户端会被映射为返回一个数组（或者List之类的类型），但是对于最后一个值是error类型的，会区别对待，该类型的返回值会被映射为异常（如果返回值为nil，则客户端不会产生异常），如果error前面只有一个返回值，该返回值是唯一返回值，而不会被映射为包含一个元素的数组。

**Comment by yuyi98** [comment]
对于大型结构类型，函数参数通常会采用引用方式，这个函数映射是否可以？不同语言如何映射？

**Comment by andot** [comment]
可以，客户端调用时只要把引用参数传递设置为true，参数就会按照引用方式来传递了。
