### ISSUE TITLE
proxy.go method方法直接panic 导致错误

### ISSUE THREAD

**Issue by chenxi2015** [hprose/hprose-golang#110]
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/13269485/187577571-e79d68a6-ab9c-46e5-9a2f-c9fd99b420ed.png">
请问这个直接panic 我在外层 如何捕获？
使用方式如下：
`
client.UseService(&method)
method.Finish(data)
`
报错误
<img width="905" alt="image" src="https://user-images.githubusercontent.com/13269485/187577771-8300b312-4ff1-4c6a-9c96-743f981e1e97.png">

**Comment by chenxi2015** [comment]
已解决

**Comment by andot** [comment]
定义方法最后一个返回参数为 `error` 类型，就会自动返回错误。如果不定义，就用  `defer` + `recovery` 来捕获。

**Comment by chenxi2015** [comment]
> 定义方法最后一个返回参数为 `error` 类型，就会自动返回错误。如果不定义，就用 `defer` + `recovery` 来捕获。

已解决 谢谢

**Comment by chenxi2015** [comment]
好的 我试试



在 2022-09-26 20:07:29，"小马哥" ***@***.***> 写道：

定义方法最后一个返回参数为 error 类型，就会自动返回错误。如果不定义，就用 defer + recovery 来捕获。
