### ISSUE TITLE
Do you plan the opportunity to work with the library through a custom transport?

### ISSUE THREAD

**Issue by monoflash** [hprose/hprose-golang#12]
This capability is essential for Google App Engine applications

I need to set an encrypted connection or the connection with the protection of their own custom algorithm and then pass it to work hprose

**Comment by andot** [comment]
You can use https or filter to encrypted the data. And we will add middleware handler support in the future.

**Comment by monoflash** [comment]
Yes, https is works.
So it was tested to use it to the server martini web server framework.
But what if there is a TCP connection is using SSL encryption, use compound in the library fails

**Comment by andot** [comment]
You can use `SetTLSConfig` on server side and `SetTLSClientConfig` on client side.
