### ISSUE TITLE
Go客户端的NewClient函数是否可以先建立连接，返回连接信息？

### ISSUE THREAD

**Issue by yuyi98** [hprose/hprose-golang#13]
```
目前的通讯操作大部分都是长连接，所以还是需要一个类似于connect的连接服务接口函数，可以判断对于服务的连接状况，这样也便于下一步的数据操作。
现在的接口实现是要在具体接口函数调用时返回连接状态信息，使用较别扭，只能自己增加一个函数用于判断连接状况，能否在NewClient函数调用中就开始建立连接，并将连接放入连接池中，并将连接信息通过error返回？
```

**Comment by andot** [comment]
RPC 的目的就是为了将业务层和通讯层分离，所以在业务层的 RPC 操作上得不到通讯层的信息是正常的。这样才便于替换底层的实现。

**Comment by yuyi98** [comment]
这与“业务层和通讯层分离”关系不大，ICE和THRIFT都有类似于创建代理对象时判断连接是否正常的机制，而不是都放到开始RPC调用时候获取连接状态。

**Comment by andot** [comment]
是有关系的，比如对于 http 客户端来说，调用可能是短连接的，所以只有调用时才会建立连接，调用完成连接可能就断了（KeepAlive 连接除外），但对于 tcp、websocket 客户端来说，调用完成之后并不会立即断开，但是空闲超时之后还是会断开，并不会一直跟服务器保持连接状态。所以在创建客户端时去建立一个连接对 RPC 来说是没有意义的。另外，创建客户端时连接正常也不代表后续通讯中连接就会一直正常，所以单纯在建立连接时去判断是不是连接正常，这样程序也是不完善的。

**Comment by yuyi98** [comment]
服务是否存在？服务是否可用？这是通讯中间件首先需要处理的获取的信息，不可能在每个RPC调用的时候都要进行判断处理，RPC调用只是判断出现通讯异常的情况（例如通讯中断），假设服务IP地址和端口号都不正确，则在每次RPC调用进行处理，不太方便。

**Comment by andot** [comment]
你说的这种跟一开始创建客户端对象时，就进行一次调用没有什么区别。如果我把这两个过程合并了，那就等于强制在创建客户端对象时进行一次通讯，对您来说，也许您觉得这样方便了您的判断，但是对于别人来说，这可能会被认为是进行了一次多余的通讯，是浪费流量，浪费时间。

合并容易，分开难。我即使不提供这个功能，用户也可以自己完成这个功能。但如果我提供了这个功能，用户想要去掉就难了，或者说根本去不掉。
