### ISSUE TITLE
参数传输性能较低

### ISSUE THREAD

**Issue by yuyi98** [hprose/hprose-golang#14]
// hps_001 project main.go
package main

import (
    "github.com/hprose/hprose-go"
)

func WriteParas(paras []int) int {
    return 1
}

func main() {
    service := hprose.NewTcpServer("tcp://127.0.0.1:2212")
    service.AddFunction("WriteParas", WriteParas)
    service.Start()
}

// hpc_001 project main.go
package main

import (
    "fmt"
    "github.com/hprose/hprose-go"
    "time"
)

type Stub struct {
    WriteParas func([]int) int
}

func main() {
    client := hprose.NewTcpClient("tcp://127.0.0.1:2212")

```
var ro *Stub
client.UseService(&ro)
paras := make([]int, 10000000)

for {
    startTm := time.Now().UnixNano()

    ro.WriteParas(paras)

    endTm := time.Now().UnixNano()

    fmt.Println("use time ", float64(endTm-startTm)/1000000.0, " ms")
}
```

}

在windows 7 64bit, go 1.5.1,硬件配置thinkpad t430s上运行，每次调用要
use time  555.0317  ms
use time  535.0306  ms
use time  546.0313  ms
use time  541.0309  ms
use time  547.0313  ms
处理效率较低

**Comment by yuyi98** [comment]
是否采用反射处理机制的打包和解析是影响处理效率的根本原因？有改进办法吗？

**Comment by andot** [comment]
这个数据量有10M大小，传输加处理，只有不到半秒钟还算慢吗？

**Comment by yuyi98** [comment]
与目前项目中采用ICE处理机制对比，吞吐量相差很大。

**Comment by andot** [comment]
ICE 有 Golang 支持吗？

**Comment by yuyi98** [comment]
是c++语言接口，ICE目前不支持Golang语言。

**Comment by andot** [comment]
C++ 和 Golang 不是一个级别的很正常。C++ 没有反射。
