### ISSUE TITLE
http hello server exits before clients connects

### ISSUE THREAD

**Issue by cocodrino** [hprose/hprose-golang#15]
Hello, I'm still newbie with go so maybe I'm doing something wrong, the problem is than when I try run this file

https://github.com/hprose/hprose-go/blob/master/examples/httphelloserver.go

using go -run httphelloserver.go

the code runs but exit immediately, seems like doesnt exist a loop, doesnt not must this code keep waiting for incoming connections?

thank so much...

**Comment by andot** [comment]
```
go run httphelloserver.go
```

No `-` before `run`.
