### ISSUE TITLE
客户端和服务器之间如何做认证？

### ISSUE THREAD

**Issue by ije** [hprose/hprose-golang#16]
谢谢 🙏

**Comment by Lao-liu** [comment]
你可以参考一下PHP版本的验证示例：

https://github.com/hprose/hprose-php/tree/master/examples/verify_demo

**Comment by ije** [comment]
@Lao-liu 谢谢 我知道通过http协议传送数据，身份认证很容易实现，但我使用的是tcp来传输数据，如果在不使用tls方式加密传输的情况下，是否还有别的相关接口可以实现认证？

**Comment by Lao-liu** [comment]
@ije 通过实现hprose.Filter 里的 InputFilter 和 OutputFilter 方法可以自己对调用请求进行自定义过滤。
