### ISSUE TITLE
No way to implement authorization

### ISSUE THREAD

**Issue by glebpom** [hprose/hprose-golang#20]
I'm trying to implement simple ip-based authorization, but it seems that it's impossible with current implementation of hprose-go - there is no access to the context from inside the exported function.

**Comment by henrypfhu** [comment]
@glebpom you can use Filter both in server and client site to implement the authorization.
You can refer to the example: tcpsessionserver.go and tcpsessionclient.go

Good luck...

**Comment by andot** [comment]
@glebpom https://github.com/hprose/hprose-go#service-event
You can use OnBeforeInvoke event to implement simple ip-based authorization. The last parameter is the context.
