### ISSUE TITLE
Access Http Header

### ISSUE THREAD

**Issue by ZhipengApv** [hprose/hprose-golang#21]
Due to security reason, our communication need to put some authentication information in http header from hprose client and get it from hprose server.
But seems there is no way to access the header directly.
Any suggestions?
Thanks

**Comment by andot** [comment]
On client, you can use [Header](https://github.com/hprose/hprose-go/blob/master/http_client.go#L82) method to get the HTTP Header and set it.
On server side, you can get it from [context.Request](https://github.com/hprose/hprose-go/blob/master/http_service.go#L230). you can use it like this:
https://github.com/hprose/hprose-go/blob/master/examples/httphelloserver.go#L12

**Comment by ZhipengApv** [comment]
Yup, the server side is fine to get. My problem is cannot get the header via client object:
client := hprose.NewClient("http://127.0.0.1:8080/")

there is no method to expose to get http client head.
