### ISSUE TITLE
新版经常出现服务崩溃

### ISSUE THREAD

**Issue by hoysoft** [hprose/hprose-golang#25]
Signal 1606415768
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1177a9 pc=0x40401e9]

runtime stack:
runtime.startpanic_m()
	/usr/local/go/src/runtime/panic.go:623 +0xfc
runtime.systemstack(0x46031f0)
	/usr/local/go/src/runtime/asm_amd64.s:314 +0xab
runtime.startpanic()
	/usr/local/go/src/runtime/panic.go:544 +0x1e
runtime.throw(0x45d680e, 0x2a)
	/usr/local/go/src/runtime/panic.go:565 +0x88
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc
runtime.sighandler(0x7fff5fbff598, 0x46b2ed6, 0x117779, 0x117779)
	/usr/local/go/src/runtime/signal_amd64x.go:167 +0x489

goroutine 1 [chan receive, 109 minutes]:
github.com/hprose/hprose-golang/rpc.(*starter).Start(0xc42056e190, 0x45c907e, 0xd)
	/Users/justinh/Development/Workspace/Golang_Path/src/github.com/hprose/hprose-golang/rpc/server.go:52 +0x2eb

goroutine 17 [syscall, 109 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 19 [syscall, 109 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 20 [chan receive, 109 minutes]:
database/sql.(*DB).connectionOpener(0xc4200b6d10)
	/usr/local/go/src/database/sql/sql.go:730 +0x4a
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x1e9

goroutine 6 [IO wait]:
net.runtime_pollWait(0x5416740, 0x72, 0x1b)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420174060, 0x72, 0xc42004bbe8, 0xc4200740a0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420174060, 0x47db580, 0xc4200740a0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420174000, 0xc420592000, 0x1000, 0x1000, 0x0, 0x47db580, 0xc4200740a0)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42007e028, 0xc420592000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc42002c180)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc42002c180, 0xc4201581c1, 0x4, 0x4, 0x423a64a, 0xc42056e160, 0x0)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x47d8e40, 0xc42002c180, 0xc4201581c1, 0x4, 0x4, 0x4, 0x2c, 0x0, 0x0)
	/usr/local/go/src/io/io.go:307 +0xa4
github.com/hprose/hprose-golang/rpc.recvData(0x47d8e40, 0xc42002c180, 0xc4201581c0, 0xc4205ae120, 0x2c)
	/Users/justinh/Development/Workspace/Golang_Path/src/github.com/hprose/hprose-golang/rpc/socket_common.go:90 +0x72
github.com/hprose/hprose-golang/rpc.(*connHandler).serve(0xc420158180, 0xc42056e000)
	/Users/justinh/Development/Workspace/Golang_Path/src/github.com/hprose/hprose-golang/rpc/socket_service.go:160 +0xfe
github.com/hprose/hprose-golang/rpc.(*SocketService).serveConn(0xc42056e000, 0x47dff00, 0xc42007e028)
	/Users/justinh/Development/Workspace/Golang_Path/src/github.com/hprose/hprose-golang/rpc/socket_service.go:99 +0x1e8
github.com/hprose/hprose-golang/rpc.(*TCPService).ServeTCPConn(0xc42056e000, 0xc42007e028)
	/Users/justinh/Development/Workspace/Golang_Path/src/github.com/hprose/hprose-golang/rpc/tcp_service.go:67 +0x1b4
created by github.com/hprose/hprose-golang/rpc.(*TCPService).ServeTCP
	/Users/justinh/Development/Workspace/Golang_Path/src/github.com/hprose/hprose-golang/rpc/tcp_service.go:93 +0xbc

**Comment by andot** [comment]
从这个错误来看，不像是个错误。最后面的信息是从客户端读取数据，如果客户端没有发送数据，服务器就会一直等待，看不出这地方为啥会触发一个 SIGSEGV 信号。

而在你错误信息中有连接数据库的代码，我想错误应该是发生在你的业务代码中的。你的业务代码触发了一个 SIGSEGV 信号，这个信号被 hprose-golang/rpc/server.go:52 在这里接收，从而导致服务崩溃的。
