### ISSUE TITLE
HTTP client hangs if server is not present

### ISSUE THREAD

**Issue by lucantolinos** [hprose/hprose-golang#26]
Hello,
I have an issue when the HTTP server is off. The HTTP client try to connect, get a "connection refused error in sendAndReceive) and i get a panic with "invalid memory or address nil".

The first 10 times (the default number of max connection) I get this error (for me It's OK since my server is missing). The next times, It hangs (I suppose the pool of connection is empty (the previous crashed call are still alive ?)).

How can I fix this issue. Is this a bug a something missing in my code.

Regards.

**Comment by andot** [comment]
Thank you for report this bug, I fixed it now.

**Comment by lucantolinos** [comment]
Thank you, work perfectly now.
