### ISSUE TITLE
请问如何使用返回机构体，然后远程调用结构体方法

### ISSUE THREAD

**Issue by fromiuan** [hprose/hprose-golang#28]
服务端代码
`
package main

import (
	"net/http"

	rpc "github.com/hprose/hprose-golang/rpc/websocket"
)

type Hello struct {
	Name string
}

func NewHello(name string) Hello {
	return Hello{Name: name}
}

func (this Hello) Hello(speak string) string {
	return "Hello " + this.Name + speak + "!"
}

func main() {
	service := rpc.NewWebSocketService()
	service.AddFunction("newhello", NewHello)
	http.ListenAndServe(":8080", service)
}
`
请问客户端如何使用初始化结构后Hello方法，

**Comment by andot** [comment]
https://github.com/hprose/hprose-golang/wiki/Hprose-%E6%9C%8D%E5%8A%A1%E5%99%A8#addmethod-%E6%96%B9%E6%B3%95

**Comment by fromiuan** [comment]
但是初始化的时候`NewHello`这个带进去一个参数，如果使用`AddMethod `方法只能导出`Hello`方法，不能使用结构体中的`Name`变量了

**Comment by andot** [comment]
NewHello 的时候带入的变量，在 Hello 方法中可以被直接使用。AddMethod 方法发布的方法是绑定到对象上的方法。所以对象上的属性（字段）都可以使用。

**Comment by fromiuan** [comment]
马哥可以按上面给个客户端例子不？

**Comment by andot** [comment]
你客户端也定义相同的这个类，然后返回的到客户端的结果也是一个 Hello 的对象，但是你调用返回的 Hello 对象上的方法是本地方法，并不是一个远程方法了。也就是说返回对象时，是把对象序列化之后返回，客户端收到之后反序列化为客户端的一个本地对象，所以这个对象上的方法是客户端本地对象上的方法。

如果你是想要发布远程对象，你直接这样发布：

```
service.AddMethod("Hello", NewHello("OOXX"), "");
```

**Comment by fromiuan** [comment]
谢谢马哥的详细解答。
