### ISSUE TITLE
rpc.NewClient 希望能返回连接是否出错的信息

### ISSUE THREAD

**Issue by zcdj1987** [hprose/hprose-golang#29]
希望能在NewClient方法后返回一个RPC连接是否出错的信息，现在无法得知当前RPC是否已经正确连接到相应的SERVER，非常蛋疼

**Comment by andot** [comment]
Hprose 在 new Client 时并不连接服务器，所以，如果你想要知道服务器是否可用，可以在服务器端发布一个用于检测服务器是否可用的方法，在创建客户端之后，调用一下那个方法就可以了。
