### ISSUE TITLE
Unix Socket Implementation

### ISSUE THREAD

**Issue by ejemba** [hprose/hprose-golang#3]
Can we imagine a unix socket version ?

**Comment by andot** [comment]
Yes, I think it can be implemented, but I don't know how to do. I have no experience in Unix Socket development.

**Comment by gogames** [comment]
Hi @ejemba , please checkout the latest pull request, it may help.

**Comment by ejemba** [comment]
Hi @gogames let me check this out !

**Comment by ejemba** [comment]
Hi @gogames I check your code and it is neaat ! 
You make a good use of golang stream abstractions.
I did not have the time to build it but it looks like it does the job !

**Comment by gogames** [comment]
@ejemba  Cool. Don't hesitate to open an issue once you find any problem.
