### ISSUE TITLE
php作为hprose的server,想让golang作为client,server的函数参数为php的数组，golang中怎么传参呢

### ISSUE THREAD

**Issue by ctrl-cli** [hprose/hprose-golang#31]
php作为hprose的server,想让golang作为client,server的函数参数为php的数组，golang中怎么传参呢。

下面是php有一个get的方法，只有一个参数，参数类型为php的数组。然后比如在其他语言的hprose,python中我传的一个dict,nodejs我传的对象,都是可以调用成功，但是在golang中不行，然后golang也刚刚开始学。懵了，弄了半天了，望指教，谢谢。

package main

import (
        "fmt"
        "github.com/hprose/hprose-golang/rpc"
)

type ApiService struct {
        get func(map[string]string) (string, error)
}

func main(){
        client := rpc.NewHTTPClient("xxx")
        var api *ApiService
        client.UseService(&api)
        params := make(map[string]string)
        params["api"] = "Session"
        params["version"] = "master"
        params["appkey"] = "xxx"
        params["appsecret"] = "xxxx"
        params["_sdk_lang"] = "hprose_golang"
        result := api.get(params)
        fmt.Printf("%v",result)
}

运行之后直接返回：
./test.go:22: multiple-value api.get() in single-value context

**Comment by andot** [comment]
问题出在你的返回值的赋值上，你的get方法定义了2个返回值，但是你的赋值语句只有一个接收参数，是这个地方错了，跟你调用成功没成功没关系，另外，你的方法字段要大写，写作Get，私有字段是无法反射的。

**Comment by ctrl-cli** [comment]
@andot 非常谢谢，已经能够调用起来
