### ISSUE TITLE
Server端接口回调

### ISSUE THREAD

**Issue by rudy-gao** [hprose/hprose-golang#34]
你好,最近看到你们的项目,我这边有一个需求是这样的,不知道能否满足?
假如我有一台client调用server端一个接口,server端处理完成step 1后,需要回调client端的一个接口,如果client端返回ok,则server端继续执行step 2,否则退出执行?
或者是这样:
假如我有一个clientManger,创建了3个client分发到3台server,每台server处理完step 1之后(各个server处理完成的时间不一致),需要回调client端的接口,询问clientManger其它server是否也处理完了step 1,如果所有的sever都处理完成step 1,则server继续执行step 2,否则等待其它server执行?

**Comment by andot** [comment]
我觉得你把server端的两步分成两个单独的RPC调用就可以简化你的问题了。

客户端调用第一步之后，根据返回结果来决定是否要进行第二步的调用，就解决了你的第一个问题。

第二个问题也是一样，客户端收到第一步的来自三台服务器的结果之后，再同时发起第二步调用就可以了。

**Comment by zouhuigang** [comment]
已转为hprose了，这个比thrift好用多了，麻痹的装了一下午环境，结果报错~~google半天没解决掉,还是这个简单易用，thrift抛弃了~~
