### ISSUE TITLE
集成iris框架该怎么做

### ISSUE THREAD

**Issue by yukui** [hprose/hprose-golang#35]
想集成iris框架，看到示例被删除了，是否不支持iris?

**Comment by dxvgef** [comment]
iris被收购了，随时可能会闭源

**Comment by andot** [comment]
删掉 iris 的例子是因为它的接口总是变来变去，连包名都三天两头的更换，导致测试无法正常跑通，所以删掉了。

**Comment by yukui** [comment]
ion 或 siris 是否可以加个示例

**Comment by andot** [comment]
https://github.com/hprose/hprose-golang/wiki/Hprose-%E6%9C%8D%E5%8A%A1%E5%99%A8#%E8%B7%9F-iris-%E6%A1%86%E6%9E%B6%E7%BB%93%E5%90%88

这里有例子，但是因为 iris 的接口和包名经常变化，所以，你理解了原理，根据你所使用的版本来自己修改一下就可以了，一共 没几行代码。应该很容易理解。

**Comment by yukui** [comment]
简单的实现了siris的使用:

```go
package main

import (
  "github.com/hprose/hprose-golang/rpc"
  "github.com/go-siris/siris"
  "github.com/go-siris/siris/context"
)

func hello(name string) string {
  return "Hello " + name + "!"
}

func main() {
  app := siris.New()

  service := rpc.NewHTTPService()
  service.AddFunction("hello", hello)

  app.Any("/", func(ctx context.Context) {
    service.ServeHTTP(ctx.ResponseWriter(), ctx.Request())
  })

  app.Listen(":8080")
}
```

**Comment by yukui** [comment]
package main

import (
	"github.com/hprose/hprose-golang/rpc"
	"github.com/kataras/iris"
)

func hello(name string) string {
	return "Hello " + name + "!"
}

func main() {
	app := iris.New()
	service := rpc.NewHTTPService()
	service.AddFunction("hello", hello)

	app.Any("/path", func(ctx iris.Context) {
		service.ServeHTTP(ctx.ResponseWriter(), ctx.Request())
	})

	app.Run(iris.Addr(":8080"))
}
