### ISSUE TITLE
如何开启pprof

### ISSUE THREAD

**Issue by pangdahua** [hprose/hprose-golang#43]
怎么打开pprof
谢谢

**Comment by andot** [comment]
这并不是要给关于 hprose 的问题，不过你问了，我给你找了一篇解答：http://www.cnblogs.com/yjf512/archive/2012/12/27/2835331.html

我只能帮到这里了。

**Comment by pangdahua** [comment]
可能没描述清楚 我import pprof 但是无法使用。

**Comment by andot** [comment]
你看我给你发的那一篇文章最后一条评论。
