### ISSUE TITLE
客户端断开连接时没有触发Unsubscribe事件

### ISSUE THREAD

**Issue by joesonw** [hprose/hprose-golang#45]
客户端断开连接时没有触发Unsubscribe事件, 而且会一直在IDList(topic) 里面

**Comment by andot** [comment]
服务器端在推送后经过 `Heartbeat` 这样一段时间之后才会从 `IDList` 中移除，并且触发 `Unsubscribe` 事件。并不是在客户端断开时，立即触发 `Unsubscribe` 事件。

**Comment by joesonw** [comment]
@andot 但是Heartbeat设置的为1也还是没触发.
