### ISSUE TITLE
没搞懂，这个跟写接口给客户端调用有什么不一样吗？求科普用这个的好处？

### ISSUE THREAD

**Issue by zouhuigang** [hprose/hprose-golang#47]

**Comment by andot** [comment]
你说的写接口是指普通的那种 HTTP API 是吧。hprose 跟传统的 HTTP API 相比，可以直接接收结构化数据的参数，返回结构化数据的结果，就像调用本地方法一样调用远程方法。而且底层通讯协议可以更换为 TCP、WebSocket 等，而不需要对服务本身的代码进行修改。

**Comment by zouhuigang** [comment]
谢谢

**Comment by zouhuigang** [comment]
已转为hprose了，这个比thrift好用多了，麻痹的装了一下午环境，结果报错~~google半天没解决掉。thrift抛弃了~~

**Comment by andot** [comment]
不客气~
