### ISSUE TITLE
有关消息订阅的代码问题

### ISSUE THREAD

**Issue by 1046102779** [hprose/hprose-golang#49]
![image](https://user-images.githubusercontent.com/20457624/30812022-5dca0fd8-a23c-11e7-9543-c6cc8d0de934.png)
这个Subscribe方法里的第二个参数ID，应该是指Client的ID，这个参数是指本客户端能帮其他客户端订阅topic？我觉得应该客户端只能给自己订阅topic，不知道这个参数放在这里的使用场景是怎么样的？ 是要这个客户端做管理节点？

**Comment by andot** [comment]
这个参数的用处就是，可以通过自己的方式来给客户端编号，然后将这个编号作为参数带入去跟服务器通讯。
