### ISSUE TITLE
客户端需要用户名和密码认证吗？我用go做服务端，php做客户端，可以连上去。但是如果发现连接信息的其他人也能连么？怎么做认证机制？

### ISSUE THREAD

**Issue by zouhuigang** [hprose/hprose-golang#51]

**Comment by andot** [comment]
这个简单，你直接发布一个 login 方法，然后让客户端先调用这个方法，之后获取一个 token，然后后面调用的参数里，都带上这个 token 去验证就可以了。验证部分你可以交给 hprose 中间件统一来做，也可以交给服务器端的 OnBeforeInvoke 事件来做。

**Comment by zouhuigang** [comment]
恩恩，谢谢，懂了。我建议还是放在Client::create('http://127.0.0.1:9999/', false)；在这个里面做认证好点，跟连mysql样的，方便点。设置用户名密码等信息，放在服务端。

**Comment by andot** [comment]
mysql 是现成的服务，使用 hprose 是你开发服务。这两者是有区别的，既然你是服务本身的提供者，那认证也应该由你来提供。也就是说，你开发的服务才是跟 mysql 等价的东西。
