### ISSUE TITLE
如何 集成 protobuf 呢？

### ISSUE THREAD

**Issue by lubaoyilang** [hprose/hprose-golang#61]
原来是用的是 grpc，想更换，可以 兼容吗？

**Comment by andot** [comment]
使用 Hprose 不需要操心序列化的问题，所以不需要自己使用 protobuf 序列化。

**Comment by lubaoyilang** [comment]
我们之前的业务，使用的了很多 pro 和 grpc 的 东西，如果是 重新开启一个项目，直接使用 Hprose那肯定 不需要操心序列化，我得意思是 如何 可以 迁移 以前 pro 的 那部分代码呢？有没有 什么比较好的方式呢？

**Comment by andot** [comment]
之前使用 grpc 编写的服务，虽然在使用 grpc 传输时，grpc 会使用 protobuf 来序列化。但是实际服务本身的代码跟 protobuf 并没有什么太大关系，只不过服务中所使用的结构体可能是由 protobuf 来生成的代码，但是这些代码在生成之后，本质上与你自己定义的结构体并没有什么太大区别（除了它内置了 protobuf 的序列化以外），所以这部分服务应该可以直接使用 hprose 来发布，除非这些结构体中包含有 hprose 不支持的序列化数据。
