### ISSUE TITLE
where is baseclient id

### ISSUE THREAD

**Issue by mohamadpk** [hprose/hprose-golang#65]
i call to AddFunction like this 

```go
service.AddFunction("GetAll", models.GetAll)
```

and GetAll source code is here

 
```go
func GetAll(t *rpc.WebSocketContext) map[string]*Object {
	t.Clients().Push("message", t.Clients().IDList("message"))
	return Objects
}
```

before return objects to client push other function in client named message

but when i use 

```go
t.Clients().Push("message", t.Clients().IDList("message"))
```

this means push message function on all client 
i need just current client not all client 
how i can detect current client id or how can access to baseclient from added function?

**Comment by andot** [comment]
```go
func GetAll(ID string, t *rpc.WebSocketContext) map[string]*Object {
	t.Clients().Push("message", ID)
	return Objects
}
```

On the client, you can pass the `client.ID()` or `client.AutoID()` to it.
