### ISSUE TITLE
将创建连接放到调用方法之前?

### ISSUE THREAD

**Issue by joesonw** [hprose/hprose-golang#68]
如果配合服务发现的话, 一开始创建客户端的时候, 或者服务提供方down掉的时候, URIList是会为空的. 此时TCPClient就会报错, 如果可以将这个检测放到Invoke的时候的话, 这样会不会更方便一些呢?

这个逻辑我发现在其他版本里面(nodejs)也是一样的.

按照现有的逻辑, 似乎只能在每次 需要在每次调用方法的时候UseService一下?

**Comment by andot** [comment]
nodejs 因为有两种创建客户端的方式，一种是直接 new 客户端对象，一种是使用 create 方法创建客户端对象。使用new方式的话，就不会检测URIList，所以 nodejs 版本不存在这个问题。go 版本我忘记只有一种创建客户端的方式了。
