### ISSUE TITLE
hprose客户端是线程安全的吗

### ISSUE THREAD

**Issue by caoym** [hprose/hprose-golang#80]
如题，使用hprose client，在存在场景下，应该每次请求重新实例化一个hprose client，还是可以在进程内复用同一个client? 如果可以复用，如何安全的获取返回的http header？

**Comment by andot** [comment]
hprose 客户端是线程安全的，不需要也不推荐每次请求重新实例化客户端对象。返回的 http header 可以通过 context.Get("httpHeader") 来获取，不过该操作只能在 hprose 的客户端中间件中进行操作，http header 返回值并不会作为结果直接返回。
