### ISSUE TITLE
客户端调用client.Unsubscribe并不会触发服务器端OnUnsubscribe，设计使然？

### ISSUE THREAD

**Issue by OliverZou** [hprose/hprose-golang#82]
看了代码，只有在断开offline时才OnUnsubscribe，这样设计有原因吗？
我想在程序过程中控制事件的订阅和取消

**Comment by andot** [comment]
这个2.0版本的推送设计的不好，3.0 已经重新设计了。这里有关于设计讨论的修改：

https://github.com/hprose/hprose/issues/8
