### ISSUE TITLE
client.Subscribe 触发server OnSubscribe事件的时间要比client.Subscribe之后的远程调用晚。

### ISSUE THREAD

**Issue by OliverZou** [hprose/hprose-golang#83]
本来client.Subscribe 之后调用其他client.remotecallXXXX,本来期望这个过程是同步的，即client.Subscribe返回后调用client.remotecallXXXX。在client.remotecallXXXX时触发服务器的 OnSubscribe事件，做好相应处理，才能保证之后的client.remotecallXXXX正确调用。但目前这点无法保证。

**Comment by OliverZou** [comment]
又翻开代码看了看，看起来应该不是hprose的问题。我先确认一下我的代码。

**Comment by OliverZou** [comment]
反复调用多次，不是每次的顺序都一样。服务器端有时候是先到remotecallXXXX 然后才是fireSubscribeEvent，有时候反过来。目前看不出是hprose的代码问题还是我的代码问题。

**Comment by OliverZou** [comment]
![1](https://user-images.githubusercontent.com/20122014/51114189-8121e800-183f-11e9-95fd-57f4ff37b93a.png)
![2](https://user-images.githubusercontent.com/20122014/51114191-82ebab80-183f-11e9-9ba2-7b870b0348f1.png)
客户端的同步调用次序是先两个client.Subscribe ，然后才是UDS_Claim
这两张图中的log记录（调试也一样）显示他们并不同步

**Comment by OliverZou** [comment]
原因：base_client.go 中使用了go client.subscribe(name, id, settings)，造成异步访问

**Comment by andot** [comment]
2.0 版本的推送在设计上不完美。3.0 已经把推送部分重写了。不过 go 版本的 hprose 3.0 目前还没开始做。所以，2.0 的这个功能暂时先别用了。等 golang 2.0 + hprose 3.0 吧 :joy:

**Comment by andot** [comment]
3.0 已发布。
