### ISSUE TITLE
获取客户端ip

### ISSUE THREAD

**Issue by ideamean** [hprose/hprose-golang#84]
package main

import (
	"github.com/hprose/hprose-golang/rpc"
)

func hello(name string) string {
        //在这里获取客户端的ip
	return "Hello " + name + "!"
}

func main() {
	server := rpc.NewTCPServer("tcp4://0.0.0.0:4321/")
	server.AddFunction("hello", hello)
	server.Start()
}

在这个示例中，如何获取客户端的ip呢？

**Comment by andot** [comment]
```go
func hello(name string, context *rpc.SocketContext) string {
	return context.Conn.RemoteAddr().String() + " Hello " + name + "!"
}
```
