### ISSUE TITLE
公共参数的传递

### ISSUE THREAD

**Issue by ideamean** [hprose/hprose-golang#86]
如果rpc调用一个方法如 getUser(id int64),  在调用时还想传递其它公共参数，但这个参数跟这个rpc方法无关联，比如一些认证的参数sign, authstring等，有什么方法可以实现？

**Comment by andot** [comment]
hprose 2.0 没有好的办法。hprose 3.0 提供了独立于传输层的 requestHeaders 和 responseHeaders 的功能。通过 requestHeaders 可以从客户端传递公共参数给服务器，通过 responseHeaders 可以从服务器传递公共参数给客户端。不过目前 hprose 3.0 只有 TypeScript、.NET 和 Dart 版本，其它语言的版本还没有开发。

Hprose 2.0 中，可以通过在自定义中间件的方式，在客户端动态为 args 添加参数，在服务器端动态获取这些附加的参数，再把参数修改为没有附加的状态。可以实现客户端到服务器端的功能参数的传递。但从服务器往客户端回传就不太好办了。

**Comment by ideamean** [comment]
好的，了解了，期待golang的3.0版本
