### ISSUE TITLE
有没有一个websocket 例子

### ISSUE THREAD

**Issue by xs23933** [hprose/hprose-golang#87]
比如广播， 服务器下针对某哥socket id 发送消息， 客户端订阅方面 websocket 都没tcp server清晰呢

**Comment by andot** [comment]
对于 hprose 来说，websocket 和 tcp 用法一样。

**Comment by xs23933** [comment]
![image](https://user-images.githubusercontent.com/92106/54534897-529fc500-49c8-11e9-97bd-d1626326bddd.png)
`package handler

import (
	"sync"
	"trade/utils"

	"github.com/davecgh/go-spew/spew"

	"github.com/gorilla/websocket"
)

var conns *sync.Map

func init() {
	conns = &sync.Map{}
}

type Work struct {
}

func (Work) Hello(name string, conn *websocket.Conn) string {
	conns.Store(utils.DeStr(name), conn)
	return "done"
}

func (Work) Test(name string) string {
	c, ok := conns.Load("x")
	if ok {
		conn := c.(*websocket.Conn)
		dat := utils.EnStr("x")
		conn.WriteMessage(websocket.BinaryMessage, []byte(dat))
	}
	spew.Dump(c, ok)
	return name
}
`

我通过这个方法获得其他的client id 然后测试主动 服务器对某客户端发信， 信息是发下去了， 也收到了， 但是没有序列化 无法call 对应方法， 这个可以手动序列化吗 ？

或有更简洁到办法吗

服务器call某个 conn 下调用方法

**Comment by andot** [comment]
hprose 中不要使用具体的传输协议。你的用法不对。hprose 使用 tcp 时也没有这样用的例子啊。

**Comment by xs23933** [comment]
那有个大致对思路么， 服务器对某client 发信，

**Comment by andot** [comment]
https://github.com/hprose/hprose-golang/blob/master/examples/push_client/push_client.go
https://github.com/hprose/hprose-golang/blob/master/examples/push_server/push_server.go

这俩是推送的例子，不过这个版本的推送不完善，不建议用。

**Comment by xs23933** [comment]
我现在根据你都这个例子在测试 js hprose-html5 subscribe  的功能
