### ISSUE TITLE
文档404

### ISSUE THREAD

**Issue by ideamean** [hprose/hprose-golang#89]
![image](https://user-images.githubusercontent.com/824662/56285516-fb694d80-6149-11e9-8315-3508c2ba355b.png)
https://github.com/hprose/hprose/blob/master/spec_zh_CN.mediawiki#%E5%BA%8F%E5%88%97%E5%8C%96%E6%A0%BC%E5%BC%8F
这个文档为何没有了呢？

**Comment by andot** [comment]
这个文件移动了，忘了更新地址了
