### ISSUE TITLE
jsonrpc_client_filter 处理 map[string]interface{} 类型参数时的问题

### ISSUE THREAD

**Issue by dtynn** [hprose/hprose-golang#9]
Hi, 我有一个如下式样的方法.  

```
type stub struct {
    IndexDoc  func(indexName, docId string, doc map[string]interface{}) error
}
```

在对 client 设置了 `NewJSONRPCClientFilter("2.0")` 之后, 调用始终报 `no Hprose RPC request`.  
而不设置 json filter 的时候, 是可以正常调用.  
# 

我进行了一些调试, 发现处理过程中, 
https://github.com/hprose/hprose-go/blob/master/hprose/jsonrpc_client_filter.go#L89
这里实际会报错: `json: unsupported type: map[interface {}]interface {}`, 导致 data 为空.  

由此处向上回溯, 产生这个结果的相关代码如下:
https://github.com/hprose/hprose-go/blob/master/hprose/jsonrpc_client_filter.go#L81  
https://github.com/hprose/hprose-go/blob/master/hprose/reader.go#L407  
https://github.com/hprose/hprose-go/blob/master/hprose/reader.go#L1751  

不知道这里是一个疏忽还是有意为之的结果?
# 

我尝试了 byref 的方式, 但是在向服务圈发起请求之前就出现了一个 
`runtime error: index out of range`
我还没有确认问题的原因.

**Comment by dtynn** [comment]
补充一下, 
前面提到的, 在我将 stub 改为

```
type stub struct {
    IndexDoc  func(indexName, docId *string, data *map[string]interface{}) error `byref:"true"`
}
```

后出现 `runtime error: index out of range` 的原因是我的测试代码中, `indexName` 和 `docId` 偷懒使用了同一个字符串指针. 

```
2015/05/20 01:27:14 runtime error: index out of range
/Users/dtynn/work/gopj/src/github.com/hprose/hprose-go/hprose/client.go:327 (0xf71bd)
    func.001: err = fmt.Errorf("%v\r\n%s", e, debug.Stack())
/Users/dtynn/work/go/src/runtime/asm_amd64.s:401 (0x3c3e5)
    call16: CALLFN(·call16, 16)
/Users/dtynn/work/go/src/runtime/panic.go:387 (0x143a8)
    gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/Users/dtynn/work/go/src/runtime/panic.go:12 (0x1353e)
    panicindex: panic(indexError)
/Users/dtynn/work/gopj/src/github.com/hprose/hprose-go/hprose/reader.go:101 (0xc6394)
    (*realReaderRefer).readRef: return r.ref[i], nil
/Users/dtynn/work/gopj/src/github.com/hprose/hprose-go/hprose/reader.go:1768 (0xd7344)
    (*Reader).readInterface: return r.readRef(r.ReadInteger(TagSemicolon))
/Users/dtynn/work/gopj/src/github.com/hprose/hprose-go/hprose/reader.go:407 (0xc872d)
    (*Reader).Unserialize: if *p, err = r.readInterface(); err == NilError {
/Users/dtynn/work/gopj/src/github.com/hprose/hprose-go/hprose/jsonrpc_client_filter.go:81 (0xc3edc)
    JSONRPCClientFilter.OutputFilter: reader.Unserialize(&params[i])
<autogenerated>:299 (0x101598)
/Users/dtynn/work/gopj/src/github.com/hprose/hprose-go/hprose/client.go:399 (0xbd60d)
    (*BaseClient).doOutput: data = client.filters[i].OutputFilter(data, context)
/Users/dtynn/work/gopj/src/github.com/hprose/hprose-go/hprose/client.go:333 (0xbc6c2)
    (*BaseClient).syncInvoke: if odata, e := client.doOutput(name, args, options, context); e != nil {
/Users/dtynn/work/gopj/src/github.com/hprose/hprose-go/hprose/client.go:319 (0xbc4a7)
    (*BaseClient).invoke: err <- client.syncInvoke(name, args, options, result, context)
/Users/dtynn/work/gopj/src/github.com/hprose/hprose-go/hprose/client.go:600 (0xf8497)
    func.003: err := <-client.invoke(name, args, options, []reflect.Value{reflect.ValueOf(&result).Elem()})
/Users/dtynn/work/go/src/reflect/value.go:482 (0x125535)
    callReflect: out := f(in)
/Users/dtynn/work/go/src/reflect/asm_amd64.s:17 (0x136936)
    makeFuncStub: CALL  ·callReflect(SB)
/Users/dtynn/work/gopj/src/github.com/tukdesk/tuksearch/client/example/example.go:28 (0x231e)
    main: log.Println(c.IndexDoc(&indexName, &indexName, &doc1))
/Users/dtynn/work/go/src/runtime/proc.go:63 (0x15ef3)
    main: main_main()
/Users/dtynn/work/go/src/runtime/asm_amd64.s:2232 (0x3e4e1)
    goexit:
```

而改成不同的字符串指针之后,  则仍然出现 `no Hprose RPC request` 的问题.

**Comment by andot** [comment]
jsonrpc 不支持 byref 方式传递数据。

map[string]interface{} 类型的数据在 jsonrpc_client_filter 中被反序列化为 map[interface {}]interface {}，是因为没有指定反序列化类型。但是在 jsonrpc_client_filter 里面，也没办法获取实际参数类型，所以这个地方虽然是个问题，但暂时也无解。

把这里的 map 换成一个 struct 指针的话，可以解决这个问题，但这个方法也许不是你想要的。

**Comment by dtynn** [comment]
非常感谢你的回答.

map 改 struct 确实有点麻烦.
事实上, 不使用 jsonrpc 的情况下, 并不会出现以上问题.

我正在考虑的一个思路, 是在本地将 数据 Marshal 化成[]byte, 再通过形似

```
type stub struct {
    IndexDoc  func(indexName, docId string, b []byte) error
}
```

的方法来调用, 服务端再做一次 Unmarshal.
不知道 hprose 中是否有类似的原生做法?
刚刚接触 hprose, 了解的很浅, 希望获得你的解答.

此外, 官网文档页上的链接似乎都是无效的, 我在 github.com/hprose 下也没有找到文档类的 repo.

**Comment by andot** [comment]
其实就像你说的，hprose 本身传递 map[string]interface{} 类型是没有问题的，传递 map[interface{}]interface{} 类型也没有问题。问题出在 json 序列化上。而 json 序列化我是修改不了的。jsonrpc 的 filter 在这里其实也只是作为一个例子来提供的，并不是 hprose 的主要功能。所以如果你只是需要传递数据的话，不用套上 jsonrpc filter 这个东西，这样效率更高，功能更强，也不会有这种类型兼容问题存在。

自己把数据序列化成 []byte，然后收到之后再自己反序列化当然也是可以的，但这种方法不推荐，这就相当于做了两层序列化，会降低运行效率。

hprose 提供了4个跟序列化有关的函数：

``` go
func Serialize(v interface{}, simple bool) ([]byte, error)
func Unserialize(b []byte, p interface{}, simple bool) error
func Marshal(v interface{}) ([]byte, error)
func Unmarshal(b []byte, p interface{}) error
```

它们的定义在这个文件中：https://github.com/hprose/hprose-go/blob/master/hprose/formatter.go

**Comment by dtynn** [comment]
非常感谢你的帮助~  :)

**Comment by andot** [comment]
不客气，没有别的问题的话，这个问题我就关闭了哈。

**Comment by andot** [comment]
为 hprose.Reader 增加了一个 JSONCompatible 属性，当它被设置为 true 时，Map 类型的数据被默认反序列化为 map[string]interface{}，这样就不会有跟 JSON 序列化不兼容的问题了。

**Comment by dtynn** [comment]
:+1:

**Comment by andot** [comment]
那拜托你帮忙测试一下，如果确实没有问题了，我就把这个问题关掉了。

**Comment by dtynn** [comment]
Hi 小马哥, 我这边做了一些简单的测试, 没有再出现上面列出的问题.
我把这个 issue 关闭了.
