### ISSUE TITLE
服务端内网调用，用哪种协议（如http,tcp)能够对高并发支持得最好？

### ISSUE THREAD

**Issue by xiaoyongcd** [hprose/hprose-golang#92]
背景：开发业务服务器端时，协议有http,tcp等。要求是能够支撑最高的并发量，用哪种协议更好呢?谢谢。

**Comment by andot** [comment]
http 比较保险，如果要快的话，可以用 fasthttp 实现，这个实现速度比 http 版本快得多，基本接近 tcp 实现的速度。不推荐 tcp 是因为目前 2.0 版本的 tcp 协议设计的不完善。3.0 对 tcp 绑定协议进行了修改，跟 3.0 实现不兼容。所以，目前不推荐使用 2.0 版本的 tcp 方式。

**Comment by andot** [comment]
hprose 3.0 已发布
