### ISSUE TITLE
想问下关于数据绑定的问题

### ISSUE THREAD

**Issue by longdahai** [hprose/hprose-golang#94]
tcp hprose version 2.0.5
php rpc client
go rpc server
php转数据如login_time
```
type model struct {
  LoginTime int
}
```
这样绑定不了，有办法解决吗

**Comment by andot** [comment]
小写的 model 是私有的，大概是不能被序列化的。

像下面这样做就可以了。

```go
type Model struct {
	LoginTime int `json:"login_time"`
}

func init() {
	io.Register((*Model)(nil), "Model", "json")
}
```

**Comment by longdahai** [comment]
> 小写的 model 是私有的，大概是不能被序列化的。
> 
> 像下面这样做就可以了。
> 
> ```go
> type Model struct {
> 	LoginTime int `json:"login_time"`
> }
> 
> func init() {
> 	io.Register((*Model)(nil), "Model", "json")
> }
> ```

谢谢
