### ISSUE TITLE
如何实现 服务端 AddFactoryMethods

### ISSUE THREAD

**Issue by tky753** [hprose/hprose-golang#95]
**AddInstanceMethods** 的instance相当于单例，如果想要每次调用都 new 一个对象，应该怎么做？
是不是只能 AddMethod，在每个method里 手动new ？
如果有一个方法 ` AddFactoryMethods(type reflect.Type, factory func()interface{}, option ...Options)`   就好了

**Comment by andot** [comment]
实现起来不够高效吧

**Comment by tky753** [comment]
好吧，那就在每个function里自己来new吧
