### ISSUE TITLE
如何优雅Mock server？

### ISSUE THREAD

**Issue by adamllv** [hprose/hprose-golang#99]
你好，我现在在给我自己的代码写测试。请问一下如何才能mock server的方法，有什么例子可以参考吗？

**Comment by andot** [comment]
https://github.com/hprose/hprose-golang/tree/v3/rpc/mock
看看这个有没有用，不过这个是 hprose 3.0 的，而且这个包的主要目的就是用来做测试的（是我做测试用的，不是给用户做测试用的）。

**Comment by adamllv** [comment]
这里面的代码我看过，测试了一下发现被测代码还是识别不到 mock server, 可能是我现在用的是v2.0.6版本的原因。我参考的代码是这段： https://github.com/hprose/hprose-golang/blob/v3/rpc/mock/mock_test.go#L45

请问一下，现在针对v2.0.6版本有mock server的例子么？

**Comment by andot** [comment]
v2.0.6 没有 mock server ，2.0.x 的测试我都是直接使用具体的服务器（比如 http 或 tcp）来写的测试。

**Comment by adamllv** [comment]
好的👌，多谢您的解答。

**Comment by adamllv** [comment]
请问下现在有计划让v2.0.6支持mock server吗？

**Comment by andot** [comment]
没有，现在的计划是赶紧把 3.0 版本完成。
